name: meshing410
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - jupyter
  - pydicom
  # - spyder
  # - vtk
  # - itk
  # - h5py
  # - meshio
  # pip install didn't work, need to fix
  # - pip:
  #   - --upgrade
  #   - gmsh

